// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2019-07-18T02:36:59.884Z

const awsmobile = {
    aws_cloud_logic_custom: [
        {
            endpoint: 'https://loavt65mvl.execute-api.us-east-1.amazonaws.com/dev',
            name: 'ApiGatewayRestApi',
            region: 'us-east-1'
        }
    ],
    aws_cognito_identity_pool_id: 'us-east-1:79daa878-fdb2-4706-9ffa-f8f9894ae2bd',
    aws_cognito_region: 'us-east-1',
    aws_project_region: 'us-east-1',
    aws_user_files_s3_bucket: 'a2c-capstone-dev-webappbucket-3ev1nop0edi5',
    aws_user_files_s3_bucket_region: 'us-east-1',
    aws_user_pools_id: 'us-east-1_ACRNWZzee',
    aws_user_pools_web_client_id: '4brji05pqvbi2qnq15vk2qumdc'
};

export default awsmobile;
