#!/bin/sh
### BEGIN INIT INFO
# Provides:          greengrass
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Starts greengrass...
### END INIT INFO
mkdir -p /greengrass/certs
mkdir -p /greengrass/config
cp /boot/certs/* /greengrass/certs/
cp /boot/config/* /greengrass/config/
/greengrass/ggc/core/greengrassd start
